"""initial_schema

Revision ID: 19938805c80f
Revises: 
Create Date: 2026-06-25 23:16:14.825378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19938805c80f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('category', sa.Enum('STRONG_MATCH', 'GOOD_MATCH', 'AVERAGE_MATCH', 'WEAK_MATCH', 'REJECT', name='candidatecategory'), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_email'), 'candidate_profiles', ['email'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('failed_files', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_weights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_weight', sa.Float(), nullable=False),
    sa.Column('experience_weight', sa.Float(), nullable=False),
    sa.Column('education_weight', sa.Float(), nullable=False),
    sa.Column('certification_weight', sa.Float(), nullable=False),
    sa.Column('project_weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_duplicates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id_1', sa.String(length=36), nullable=False),
    sa.Column('candidate_id_2', sa.String(length=36), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('duplicate_status', sa.Enum('PENDING_REVIEW', 'MERGED', 'IGNORED', 'DIFFERENT_PERSON', name='duplicatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id_1'], ['candidate_profiles.id'], ),
    sa.ForeignKeyConstraint(['candidate_id_2'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_duplicates_candidate_id_1'), 'candidate_duplicates', ['candidate_id_1'], unique=False)
    op.create_index(op.f('ix_candidate_duplicates_candidate_id_2'), 'candidate_duplicates', ['candidate_id_2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_duplicates_candidate_id_2'), table_name='candidate_duplicates')
    op.drop_index(op.f('ix_candidate_duplicates_candidate_id_1'), table_name='candidate_duplicates')
    op.drop_table('candidate_duplicates')
    op.drop_table('scoring_weights')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_candidate_profiles_email'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
