"""add stripe_session_id to credit_transactions

Revision ID: b45a9dc4c84e
Revises: 56f91f5ff0ed
Create Date: 2026-07-13 00:22:51.831077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45a9dc4c84e'
down_revision: Union[str, Sequence[str], None] = '56f91f5ff0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=False)
    op.add_column('credit_transactions', sa.Column('stripe_session_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_credit_transactions_stripe_session_id'), 'credit_transactions', ['stripe_session_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_user_id'), 'processing_jobs', ['user_id'], unique=False)
    op.alter_column('users', 'credits_remaining',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'credits_remaining',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_processing_jobs_user_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_credit_transactions_stripe_session_id'), table_name='credit_transactions')
    op.drop_column('credit_transactions', 'stripe_session_id')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    # ### end Alembic commands ###
