"""add raw_texts to processing_jobs

Revision ID: cb5c7cfa0b27
Revises: ea2d47f5601e
Create Date: 2026-07-15 00:39:09.785570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5c7cfa0b27'
down_revision: Union[str, Sequence[str], None] = 'ea2d47f5601e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('raw_texts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'raw_texts')
    # ### end Alembic commands ###
