"""add unique constraint on stripe_session_id

Revision ID: ea2d47f5601e
Revises: b45a9dc4c84e
Create Date: 2026-07-13 00:32:21.953567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2d47f5601e'
down_revision: Union[str, Sequence[str], None] = 'b45a9dc4c84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_transactions_stripe_session_id'), table_name='credit_transactions')
    op.create_unique_constraint(None, 'credit_transactions', ['stripe_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit_transactions', type_='unique')
    op.create_index(op.f('ix_credit_transactions_stripe_session_id'), 'credit_transactions', ['stripe_session_id'], unique=False)
    # ### end Alembic commands ###
